# This is a basic workflow to help you get started with Actions.

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the main repo under $GITHUB_WORKSPACE, so your job can access it
      - id: checkoutmain
        name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: main
          fetch-depth: 0 #this is needed to fetch all the tags
      # Checks-out external repo under $GITHUB_WORKSPACE, so your job can access it
      - id: checkoutremote
        name: Checkout remote repo
        uses: actions/checkout@v4
        with:
          path: website
          repository: ${{ secrets.MAIN_REPO_URI }}
          ref: 'master'
          token: ${{ secrets.MAIN_REPO_TOKEN }}
          
      - id: createnewpost
        name: Create new file in repo
        run: |
          echo "Creates a new file in repo or atleast tries to"
          cd $GITHUB_WORKSPACE
          cd website/content/posts
          date=$(date '+%Y-%m-%d')
          fileName=release-dummy-$date.md
          touch $fileName
          ls
      - id: createchangelog
        name: Create Changelog
        run: |
          cd $GITHUB_WORKSPACE
          cd main
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          #echo $LAST_TAG
          git log --no-merges --pretty=format:'%n%s' $LAST_TAG..HEAD > "changelog.txt"
          cp changelog.txt $GITHUB_WORKSPACE/changelog.txt
          #git describe --tags --abbrev=0 --always
          #git log --no-merges --pretty=format:"%s" $(git describe --tags --abbrev=0)... > "changelog.txt"
          
      - name: Put content in file
        run: |
          cd $GITHUB_WORKSPACE
          cd website/content/posts
          date=$(date '+%Y-%m-%d')
          fileName=release-dummy-$date.md
          echo "Directory: "
          ls
          echo "---" > "$fileName"
          echo "title: \"release dummy $date\" " >> "$fileName"
          echo "date: 2018-07-21T10:58:53+01:00" >> "$fileName"
          echo "draft: false" >> "$fileName"
          echo "---" >> "$fileName"
          echo "" >> "$fileName"
          ../../changelog.txt >> "$fileName"
          echo "" >> "$fileName"
          echo "New release created today, go check it out" >> "$fileName"
          echo "" >> "$fileName"
          echo "<img src=\"https://raw.githubusercontent.com/neisep/guidgenerator/master/software.png\"/>" >> "$fileName"

      - name: List directories
        run: |
          echo "working directory"
          ls
          echo "workspace dir"
          cd $GITHUB_WORKSPACE
          ls
          cd website
          ls
      - uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: "update release from dummy"
          repository: website
